browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

clean:
  # The jekyll build dir
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  # The two comments above this one came from the template.
  # We copy all JS and SCSS because Google Chrome Inspect will tell you where the style is located within the sass structure.
  assets:
    # all files below the assets dir
    # everything gets copied to site build becuase some JS files are linked directly into pages and not compiled into all.min.js)
    - "assets/**/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks)
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

# Gulp task for travis to copy and minify static assets (i.e. image assets)
travisCopy:
  assets:
    - "assets/**/*"
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running travisCopy"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

# Gulp task for travis to compile and minify main.css from Sass.
travisSass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running travisSass"
  src: "assets/scss/main.scss"

# Gulp task to create stylesheet for custom CloudCannon editor styles (CMS customizations)
contentSass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Content Sass"
  src: "assets/scss/content.scss"

# Gulp task for travis-ci to create stylesheet for custom CloudCannon editor styles (CMS customizations)
travisContentSass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running travisContentSass"
  src: "assets/scss/content.scss"

# Main JavaScript compile task (gulp_tasks/script.js)
javascript:
  dest:
    jekyllRoot: "assets/js/script/"
    buildDir: "_site/assets/js/script/"
  filename: "all.min.js"
  notification: "Running JavaScript"
  src:
    # Exclusions: (!exclaim to exclude)
    # Inclusions: (included in JS compile)
    - "!assets/js/script/test.js" # test js file
    - "!assets/js/script/breadcrumb.js"
    - "assets/js/script/sliders.js"
    - "assets/js/script/lazyLoad.js"
    - "assets/js/script/currentPage.js"
    - "assets/js/script/searchToggle.js"
    - "assets/js/script/shopSmile.js"
    - "assets/js/script/scrollFunction.js"
    - "assets/js/script/subNav.js"
    - "assets/js/script/walkText.js"
    - "assets/js/script/tabLink.js"
    - "assets/js/script/scholarshipTime.js"
    - "assets/js/script/accordian.js"
    - "assets/js/script/boldFont.js"
    - "assets/js/script/jumpLinkFix.js"

tableScript:
  dest:
    jekyllRoot: "assets/js/table/"
    buildDir: "_site/assets/js/table/"
  filename: "spreadsheet.min.js"
  notification: "Running tableScript"
  src:
    # Exclusions: (!exclaim to exclude)
    # Inclusions: (included in JS compile)
    - "assets/js/table/scholarshipTable.js"

# Gulp task for main travis JS compile/uglify of all.min.js.
travisScript:
  dest:
    jekyllRoot: "assets/js/"
    buildDir: "_site/assets/js/"
  filename: "all.min.js"
  notification: "Running travisScript"
  src:
    # Exclusions: (!exclaim to exclude)
    # Inclusions: (included in JS compile)
    - "assets/js/test.js" # test js file
    - "assets/js/sliders.js"
    - "assets/js/lazyLoad.js"
    - "assets/js/currentPage.js"
    - "!assets/js/scholarshipTable.js"
    - "!assets/js/scholarships.js"
    - "!assets/js/sortable.js"
    - "!assets/js/spreadsheet.js"

sitemap:
  src:
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
    - "_site/**/*.pdf"
    - "_site/**/**/*.pdf"
  siteUrl:
    - "https://foundation.kcc.edu"

# Gulp task for travis-ci to create sitemap on production builds (`$ gulp --production`).
travisSitemap:
  src:
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
    - "_site/**/*.pdf"
    - "_site/**/**/*.pdf"
  siteUrl:
    - "https://foundation.kcc.edu"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images: "assets/img/**/*"
  javascript:
    - "assets/js/script/all.min.js"
    - "assets/js/script/*.js"
  tableScript:
    - "assets/js/table/spreadsheet.min.js"
    - "assets/js/table/*.js"
  sass: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,_alerts}/**/*.{md,html,yml,xml}"
    # All these subfolders are added because the watch task was not looking deep enough
    # !exlclusions:
    - "!_site/**/*.*"
    - "!assets/**/*.*"
    - "_alumnis/*.md"
    - "about/**"
    - "about/**/**"
    - "events/**"
    - "events/**/**"
    - "alumni/**"
    - "alumni/**/**"
    - "scholarships/**"
    - "scholarships/**/**"
    - "give/**"
    - "give/**/**"
